name: aoc_workspace
description: Advent of Code 2025 Workspace
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/cli
  - packages/core
  - packages/day_builder
  - packages/frontend
  - packages/input
  - packages/input_s3
  - packages/solutions

dev_dependencies:
  aoc_input_s3: any
  dotenv: ^4.2.0
