name: aoc
description: Advent of Code 2025 solutions
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  aoc_core: any
  aoc_input: any
  async: ^2.11.0
  logger: ^2.0.0
  memoized: ^2.0.0
  meta: ^1.0.0
  squadron: ^7.0.0

dev_dependencies:
  aoc_input_s3: any
  build_runner: ^2.4.0
  day_builder: any
  dotenv: ^4.2.0
  lints: ^6.0.0
  squadron_builder: 9.0.0
  test: ^1.0.0
