name: Workflow
on:
  push:
    branches: [ main ]
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v2

  test-foundation:
    name: Test ${{ matrix.path }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: packages/core
          - path: packages/input
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/setup-pub-cache
      - name: Get dependencies
        run: flutter pub get --enforce-lockfile
      - name: Run tests
        working-directory: ${{ matrix.path }}
        run: dart test --file-reporter json:test-results.json --coverage=.coverage .
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Convert to LCOV
        run: dart pub global run coverage:format_coverage --report-on=lib --report-on=${{ matrix.path }}/lib --lcov -o ./.coverage/lcov.info -i ${{ matrix.path }}/.coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage/lcov.info
          disable_search: true

  test-solutions:
    name: Test solutions
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/setup-pub-cache
      - name: Get dependencies
        run: flutter pub get --enforce-lockfile
      - name: Generate code
        working-directory: packages/solutions
        run: dart run build_runner build
      - name: Run tests
        working-directory: packages/solutions
        run: dart test --file-reporter json:test-results.json --coverage=.coverage .
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_INPUT_BUCKET_NAME: ${{ secrets.S3_INPUT_BUCKET_NAME }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Convert to LCOV
        run: dart pub global run coverage:format_coverage --report-on=lib --report-on=packages/solutions/lib --lcov -o ./.coverage/lcov.info -i ./packages/solutions/.coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage/lcov.info
          disable_search: true

  check-format:
    name: Check Format
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/setup-pub-cache
      - name: Get dependencies
        run: flutter pub get --enforce-lockfile
      - name: Check formatting
        run: |
          dart format packages/*/bin packages/*/lib packages/*/test packages/*/tool tool --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/setup-pub-cache
      - name: Get dependencies
        run: flutter pub get --enforce-lockfile
      - name: Generate code
        working-directory: packages/solutions
        run: dart run build_runner build
      - name: Run Analysis
        run: dart analyze --fatal-infos

  build-cli:
    name: Build Binary
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - required-meta
      - check-format
      - lint
      - test-foundation
      - test-solutions
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: linux-amd64
            runner: ubuntu-24.04
          - id: linux-arm64
            runner: ubuntu-24.04-arm
          - id: macos-amd64
            runner: macos-15-intel
          - id: macos-arm64
            runner: macos-15
          - id: win-amd64
            runner: windows-2025
            filename: advent.exe
          - id: win-arm64
            runner: windows-11-arm
            filename: advent.exe
    runs-on: ${{ matrix.runner }}
    env:
      # renovate: datasource=docker depName=dart
      DART_VERSION: 3.10.2
    steps:
      - uses: actions/checkout@v6
      - name: Set up Dart SDK cache
        uses: actions/cache@v4
        with:
          path: ${{ env.RUNNER_TOOL_CACHE }}/dart/${{ env.DART_VERSION }}
          key: dart-${{ env.DART_VERSION }}-${{ runner.os }}-${{ runner.arch }}
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Prepare workspace
        env:
          PUBSPEC_OVERRIDE: |
            workspace:
              - packages/cli
              - packages/core
              - packages/day_builder
              - packages/input
              - packages/input_s3
              - packages/solutions
        run: |
          printenv PUBSPEC_OVERRIDE > pubspec_overrides.yaml
          # Not enforcing lockfile because we're excluding the Flutter frontend here
          dart pub get
          mkdir output
      - name: Generate code
        working-directory: packages/solutions
        run: dart run build_runner build
      - name: Compile binary
        working-directory: packages/cli
        run: dart compile exe bin/main.dart -o "${{ github.workspace }}/output/${{ matrix.filename || 'advent' }}"
      - if: runner.os != 'Windows'
        run: chmod +x "output/advent"
      - uses: actions/upload-artifact@v5
        if: github.ref_name == github.event.repository.default_branch
        with:
          name: binary-${{ matrix.id }}
          path: output/*

  build-frontend:
    runs-on: ubuntu-24.04
    needs:
      - test-foundation
      - test-solutions
      - lint
      - check-format
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - uses: ./.github/actions/setup-pub-cache
      - name: Install Dart dependencies
        run: flutter pub get --enforce-lockfile
      - name: Generate code
        working-directory: packages/solutions
        run: dart run build_runner build
      - name: Build web package
        working-directory: packages/frontend
        run: flutter build web --wasm --base-href="/2025/"
      - name: Store build result
        uses: actions/upload-artifact@v5
        with:
          name: web-app
          path: packages/frontend/build/web

  all-checks-passed:
    runs-on: ubuntu-24.04
    if: "!cancelled() && github.event_name == 'pull_request'"
    needs:
      - test-foundation
      - test-solutions
      - check-format
      - lint
      - build-frontend
    steps:
      - run: |
          if [ "true" == "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}" ]
          then
            echo "A required job failed"
            exit 1
          else
            echo "All required jobs passed"
          fi

  deploy-frontend:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    needs:
      - build-frontend
    concurrency: production
    environment:
      name: Production
      url: https://aoc.bjoernpetersen.net/2025/
    container: rclone/rclone:1.72
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: web-app
      - name: Save rclone config
        env:
          CONFIG: |
            [r2]
            type = s3
            provider = Cloudflare
            access_key_id = ${{ secrets.S3_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.S3_SECRET_ACCESS_KEY }}
            endpoint = ${{ secrets.S3_ENDPOINT }}
        run: |
          mkdir -p /config/rclone
          echo "$CONFIG" > /config/rclone/rclone.conf
      - name: Copy web package to bucket
        run: rclone sync "$PWD" "r2:${{ secrets.S3_PUBLIC_BUCKET_NAME }}/2025/"
